-- MySQL Script generated by MySQL Workbench
-- Thu Dec  2 18:41:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sismarket_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sismarket_db` ;

-- -----------------------------------------------------
-- Schema sismarket_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sismarket_db` DEFAULT CHARACTER SET utf8 ;
USE `sismarket_db` ;

-- -----------------------------------------------------
-- Table `sismarket_db`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismarket_db`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sismarket_db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismarket_db`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nom_usuario` VARCHAR(100) NOT NULL,
  `tipo_documento` VARCHAR(45) NULL,
  `num_documento` INT NULL,
  `telefono` INT NULL,
  `email` VARCHAR(60) NULL,
  `password` VARCHAR(45) NULL,
  `nom_apell` VARCHAR(100) NULL,
  `rol_id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_rol_idx` (`rol_id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `sismarket_db`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sismarket_db`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismarket_db`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sismarket_db`.`medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismarket_db`.`medida` (
  `id_medida` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_medida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sismarket_db`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismarket_db`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(13) NULL,
  `nombre` VARCHAR(100) NULL,
  `categoria_id_categoria` INT NOT NULL,
  `medida_id_medida` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_producto_categoria1_idx` (`categoria_id_categoria` ASC) VISIBLE,
  INDEX `fk_producto_medida1_idx` (`medida_id_medida` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria1`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `sismarket_db`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_medida1`
    FOREIGN KEY (`medida_id_medida`)
    REFERENCES `sismarket_db`.`medida` (`id_medida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sismarket_db`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismarket_db`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `razon_social` VARCHAR(100) NULL,
  `ruc` VARCHAR(11) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` INT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sismarket_db`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismarket_db`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `tipo_documento` VARCHAR(11) NULL,
  `direccion` VARCHAR(80) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sismarket_db`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismarket_db`.`compra` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `proveedor_id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_compra`, `proveedor_id_proveedor`),
  INDEX `fk_compra_proveedor1_idx` (`proveedor_id_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_compra_proveedor1`
    FOREIGN KEY (`proveedor_id_proveedor`)
    REFERENCES `sismarket_db`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sismarket_db`.`registro_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismarket_db`.`registro_compra` (
  `id_producto_proveedor` INT NOT NULL AUTO_INCREMENT,
  `producto_id_producto` INT NOT NULL,
  `cantidad` INT NULL,
  `precio` DECIMAL(11,2) NULL,
  `compra_idcompra` INT NOT NULL,
  PRIMARY KEY (`id_producto_proveedor`, `producto_id_producto`),
  INDEX `fk_producto_has_proveedor_producto1_idx` (`producto_id_producto` ASC) VISIBLE,
  INDEX `fk_registro_compra_compra1_idx` (`compra_idcompra` ASC) VISIBLE,
  CONSTRAINT `fk_producto_has_proveedor_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `sismarket_db`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_compra_compra1`
    FOREIGN KEY (`compra_idcompra`)
    REFERENCES `sismarket_db`.`compra` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sismarket_db`.`comprobante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismarket_db`.`comprobante` (
  `id_comprobante` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id_comprobante`, `usuario_id_usuario`, `cliente_id_cliente`),
  INDEX `fk_usuario_has_cliente_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  INDEX `fk_usuario_has_cliente_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_cliente_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `sismarket_db`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_cliente_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `sismarket_db`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sismarket_db`.`registro_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismarket_db`.`registro_venta` (
  `id_producto_cliente` INT NOT NULL AUTO_INCREMENT,
  `producto_id_producto` INT NOT NULL,
  `cantidad` INT NULL,
  `precio` DECIMAL(11,2) NULL,
  `comprobante_serie` INT NOT NULL,
  PRIMARY KEY (`id_producto_cliente`, `producto_id_producto`),
  INDEX `fk_cliente_has_producto_producto1_idx` (`producto_id_producto` ASC) VISIBLE,
  INDEX `fk_registro_venta_comprobante1_idx` (`comprobante_serie` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_producto_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `sismarket_db`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_venta_comprobante1`
    FOREIGN KEY (`comprobante_serie`)
    REFERENCES `sismarket_db`.`comprobante` (`id_comprobante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sismarket_db`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismarket_db`.`inventario` (
  `id_inventario` INT NOT NULL,
  `fecha_vencimiento` DATE NULL,
  `cantidad` INT NULL,
  `producto_id_producto` INT NOT NULL,
  PRIMARY KEY (`id_inventario`, `producto_id_producto`),
  INDEX `fk_inventario_producto1_idx` (`producto_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_inventario_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `sismarket_db`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
